spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant?characterEncoding=utf-8&useSSL=false
    username: root
    password: tang2017
  session:
    store-type: none
security:
  basic:
    enabled: false
