spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/conzen-security?characterEncoding=utf-8&useSSL=false
    username: root
    password: tang2017
  session:
    store-type: none
server:
  session:
    timeout: 3600
logging:
  level:
#    org.springframework: debug


conzen:
  security:
    browser:
#      login-page: /demo-login.html # TODO 不加/会无限重定向
#      login-type: JSON
       logout-page: /demo-logout.html
       sign-up-url: /demo-signUp.html
#    code:
#      image:
#        width: 200
#        height: 60
#        urls: /user,/user/*
    social:
      weixin:
        provider-id: weixin
        app-id: wxfcba7e4cbc7a491b
        app-secret: 0eed4198a78988bfdbc04493e79022b1
      qq:
        provider-id: qq
        app-id: 101484342
        app-secret: 74ec2e515128b06ee58804aac0e3177d
      filter-processes-url: /auth
    oauth2:
      clients[0]:
        client-id: conzen
        client-secret: 123456
        access-token-validity-seconds: 3600
      clients[1]:
        client-id: less
        client-secret: 123456
